#!/usr/bin/env bun
import { $ } from "bun"
import { homedir } from "os"
import { existsSync } from "fs"
import fs from "fs/promises"
import path from "path"

// Local dev deploy: install the local jollicode CLI as the global `jollicode`,
// then package the VS Code extension and install it. Pass an editor command to
// install into something other than VS Code, e.g. `bun run dev:deploy cursor`.
//
// The CLI is installed as a source shim (bun runs src/index.ts) rather than a
// compiled `bun build --compile` binary: the compiled binary currently crashes
// ~3s after TUI start with an AbortError ("Unexpected server error"), while the
// source run is stable (tracked in JOLLI-2474). The shim also makes code changes
// take effect with no rebuild.
//
// Cross-platform: writes a POSIX /bin/sh shim (macOS/Linux, and Git Bash on
// Windows) plus .cmd/.ps1 shims on Windows, whose native shells ignore the
// shebang and the executable bit.

const usage = 'Usage: bun run dev:deploy [editor]   (editor defaults to "code", e.g. "cursor" | "windsurf" | "codium")'

const args = process.argv.slice(2)
if (args.includes("--help") || args.includes("-h")) {
  console.log(usage)
  process.exit(0)
}

const unknown = args.find((arg) => arg.startsWith("-"))
if (unknown) {
  console.error(`Unknown option: ${unknown}`)
  console.error(usage)
  process.exit(1)
}

const root = path.resolve(import.meta.dirname, "..")

// Marker embedded in generated shims so a later run can tell its own output apart
// from a real `jollicode` install and refuse to clobber the latter.
const SHIM_MARKER = "# Generated by `bun run dev:deploy`."

await linkCliShim()
await buildAndInstallExtension(args[0] ?? "code")

console.log("\n✅ dev:deploy complete")

async function linkCliShim() {
  const opencode = path.join(root, "packages/opencode")
  // Fail with an actionable message instead of a raw resolver error on a fresh
  // clone where workspace deps aren't installed yet.
  if (!existsSync(path.join(opencode, "node_modules/@opentui/solid"))) {
    throw new Error("Workspace deps not installed. Run `bun install` at the repo root first, then re-run dev:deploy.")
  }
  // Resolve @opentui/solid's preload absolutely so the shim works from any cwd;
  // it applies the solid JSX runtime that packages/opencode/bunfig.toml's
  // preload normally provides. Without it the TUI's JSX falls back to react.
  const preload = Bun.resolveSync("@opentui/solid/preload", opencode)
  const index = path.join(opencode, "src/index.ts")

  const binDir = path.join(process.env.BUN_INSTALL ?? path.join(homedir(), ".bun"), "bin")
  await fs.mkdir(binDir, { recursive: true })

  // POSIX shim: used by macOS/Linux and by Git Bash/MSYS on Windows.
  const posix = path.join(binDir, "jollicode")
  await writeShim(
    posix,
    [
      "#!/bin/sh",
      `${SHIM_MARKER} Runs the local jollicode CLI from source.`,
      `exec bun --preload ${JSON.stringify(preload)} ${JSON.stringify(index)} "$@"`,
      "",
    ].join("\n"),
  )
  await fs.chmod(posix, 0o755)

  // Native Windows shells ignore the shebang and the executable bit, so add
  // .cmd/.ps1 shims that PATHEXT resolves for cmd and PowerShell. CRLF endings
  // and %*/@args forward every argument through to the source run.
  if (process.platform === "win32") {
    await writeShim(
      path.join(binDir, "jollicode.cmd"),
      [
        "@echo off",
        `rem ${SHIM_MARKER} Runs the local jollicode CLI from source.`,
        `bun --preload "${preload}" "${index}" %*`,
        "",
      ].join("\r\n"),
    )
    await writeShim(
      path.join(binDir, "jollicode.ps1"),
      [
        `${SHIM_MARKER} Runs the local jollicode CLI from source.`,
        `& bun --preload "${preload}" "${index}" @args`,
        "exit $LASTEXITCODE",
        "",
      ].join("\r\n"),
    )
  }

  console.log(`→ Linked jollicode → ${index} (source shim in ${binDir})`)

  const active = Bun.which("jollicode")
  if (!active || path.dirname(active) !== binDir) {
    console.warn(`⚠ PATH resolves jollicode to ${active ?? "nothing"}, not the shim in ${binDir}. Check your PATH order.`)
  }
}

// Writes a shim, refusing to clobber a file that isn't a previously-generated
// shim. Reads only the head, since a real install could be a large binary.
async function writeShim(file: string, contents: string) {
  if (existsSync(file) && !(await Bun.file(file).slice(0, 256).text()).includes(SHIM_MARKER)) {
    throw new Error(
      `Refusing to overwrite ${file}: it is not a dev:deploy shim (no generated marker). ` +
        `Remove it manually or point BUN_INSTALL at a different prefix, then re-run.`,
    )
  }
  await fs.rm(file, { force: true })
  await Bun.write(file, contents)
}

async function buildAndInstallExtension(editor: string) {
  const dir = path.join(root, "sdks/vscode")
  if (!existsSync(path.join(dir, "node_modules"))) {
    console.log("→ Installing extension deps…")
    await $`bun install`.cwd(dir)
  }
  console.log("→ Packaging VS Code extension (.vsix)…")
  await $`bunx @vscode/vsce@4.0.0 package --no-dependencies --skip-license -o dist/jollicode.vsix`.cwd(dir)

  const bin = resolveEditor(editor)
  // Uninstall first: reinstalling the same version leaves the editor showing the
  // previously cached icon/metadata. A clean uninstall+install avoids that (a
  // full editor restart is still needed to drop the in-memory icon cache).
  console.log(`→ Reinstalling extension into ${editor}…`)
  await $`${bin} --uninstall-extension jolli.jollicode`.cwd(dir).nothrow()
  await $`${bin} --install-extension dist/jollicode.vsix --force`.cwd(dir)
}

function resolveEditor(name: string) {
  const onPath = Bun.which(name)
  if (onPath) return onPath
  const app = (bundle: string, bin: string) => `/Applications/${bundle}.app/Contents/Resources/app/bin/${bin}`
  const bundles: Record<string, string> = {
    code: app("Visual Studio Code", "code"),
    cursor: app("Cursor", "cursor"),
    windsurf: app("Windsurf", "windsurf"),
    codium: app("VSCodium", "codium"),
  }
  const fallback = bundles[name]
  if (fallback && existsSync(fallback)) return fallback
  throw new Error(
    `Could not find the "${name}" CLI on PATH. Pass an editor command (e.g. "bun run dev:deploy cursor") ` +
      `or add its CLI to PATH.`,
  )
}
